### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by kevjp** [robinandeer/chanjo-report#22]
Installed chanjo report as instructed. Tried to generate a report based on the sqlite db generated by running the demo  at http://chanjo.readthedocs.org/en/latest/introduction.html . Ran the command:

`chanjo report --render pdf --samples "sample2" > ./out.pdf`

but was returned the error

```python
[2016-02-10 22:26:46,830] INFO    : chanjo.cli.root          : version 3.2.1
Traceback (most recent call last):
  File "/usr/local/bin/chanjo", line 9, in <module>
    load_entry_point('chanjo==3.2.1', 'console_scripts', 'chanjo')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chanjo_report-2.4.0-py2.7.egg/chanjo_report/cli/core.py", line 45, in report
    click.echo(render_method(api, options=context.obj))
  File "/usr/local/lib/python2.7/dist-packages/chanjo_report-2.4.0-py2.7.egg/chanjo_report/interfaces/pdf/core.py", line 22, in render_pdf
    app = create_app(config=config)
  File "/usr/local/lib/python2.7/dist-packages/chanjo_report-2.4.0-py2.7.egg/chanjo_report/server/app.py", line 18, in create_app
    configure_extensions(app)
  File "/usr/local/lib/python2.7/dist-packages/chanjo_report-2.4.0-py2.7.egg/chanjo_report/server/app.py", line 34, in configure_extensions
    api.init_app(app)
  File "/usr/local/lib/python2.7/dist-packages/chanjo/store/api.py", line 37, in init_app
    self.connect(db_uri=uri)
  File "/usr/local/lib/python2.7/dist-packages/chanjo/store/core.py", line 72, in connect
    if 'mysql' in db_uri:
TypeError: argument of type 'NoneType' is not iterable
```

Not exactly sure what is wrong, any help much appreciated.

**Comment by robinandeer** [comment]
I'll look into it :)

**Comment by robinandeer** [comment]
This was my bad, I've release an update to Chanjo-Report (v2.4.2) that addresses the issue. I was fetch the database URI from the wrong location :P

Good call, thank you for the bug report!!
